### ISSUE TITLE
Add User Authentication and Authorization

### ISSUE THREAD

**Issue by farewelldave** [StrongholdData/Stronghold-Cloud-Reporting#2]
Need to add ability and requirement for users to login in order to view any of the contents.

Including:
- [ ] Add User Authentication and framework (login/logout model/view, etc.)
- [ ] Add User Authorization roles (Staff/Superuser)
- [ ] Set sane defaults for each view and access based on roles above
