### ISSUE TITLE
Add Django Auth LDAP

### ISSUE THREAD

**Issue by farewelldave** [StrongholdData/Stronghold-Cloud-Reporting#3]
Need to add ability to authenticate with LDAP using django-auth-ldap & pyldap

Including:
- [ ] LDAP and LDAPS connectivity ability
- [ ] Ability to map groups in Django to LDAP (Staff, Superusers, etc.)
- [ ] Ensure this also ties into Django admin auth
